framework:
#    default_locale: '%locale%'
#    translator:
#        default_path: '%kernel.project_dir%/translations'
#        fallbacks:
#            - '%locale%'
    default_locale: 'en'
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks: ['fr']
